dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - V8=6.3
  matrix:
    - PHP=7.1
    - PHP=7.1 TEST_PHP_ARGS=-m
    - PHP=7.2
    - PHP=7.2 TEST_PHP_ARGS=-m

before_install:
  - docker build -t ${TRAVIS_REPO_SLUG}:${V8}-${PHP} --build-arg V8=${V8} --build-arg PHP=${PHP} .

script:
  - docker run -e TEST_PHP_ARGS ${TRAVIS_REPO_SLUG}:${V8}-${PHP} bash -c "make test | tee result.txt; ./test-report.sh"
